version: 2.1
orbs:
  aws-cli: circleci/aws-cli@4.0.0
executors:
  aws-executor:
    docker:
      - image: 'cimg/node:22.5.1'
    environment:
      AWS_REGION: 'us-east-1'
jobs:
  build:
    executor: default
    steps:
      - aws-cli/setup:
          aws_access_key_id: AWS_ACCESS_KEY
          aws_secret_access_key: AWS_ACCESS_SECRET
          aws_region: AWS_REGION_NAME
      - checkout
      - run:
          name: 'Build CDK App'
          command: | 
            npm install
            npm run build
      - run:
          name: 'cdk_deploy'
          command: npm run ci_deploy
workflow:
  cdk-deployment:
    jobs:
      - build